[package]
name = "parties-rs"
version = "0.1.18"
edition = "2024"

[dependencies]
bip39 = "2.2.2"
bytes = "1"
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
cpal = "0.18.0"
ed25519-dalek = "2.2.0"
getrandom = "0.4.2"
lurq = { version = "0.12.3", features = ["resources", "winit", "image", "wgpu", "dx12", "devtools", "i18n", "serde", "clipboard", "tokio", "router", "form", "svg"] }
minimp3 = "0.6.1"
opus = "0.3.1"
quinn = "0.11"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
semver = "1"
serde_json = "1"
sha2 = "0.11.0"
sonora = "0.1.0"
tokio = { version = "1", features = ["rt-multi-thread", "signal", "sync", "time"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "time"] }
rdev = "0.5.3"
rfd = "0.15.4"
xcap = "0.9.6"
zip = { version = "4", default-features = false, features = ["deflate"] }
sentry = { version = "0.48.2", default-features = false, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "rustls"] }
sentry-tracing = "0.48.2"
parking_lot = "0.12.5"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.8.7"
core-media-sys = "0.1.2"
core-video-sys = "0.1.4"
flate2 = "1"
tar = "0.4"

[target.'cfg(target_os = "macos")'.build-dependencies]
cc = "1.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Graphics_Dxgi", "Win32_Graphics_Gdi", "Win32_Media_Audio", "Win32_Media_MediaFoundation", "Win32_Media_Multimedia", "Win32_Storage_Xps", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Diagnostics_Debug", "Win32_System_Kernel", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_System_Variant", "Win32_UI_WindowsAndMessaging"] }
windows-core = "0.62.2"

[target.'cfg(windows)'.build-dependencies]
cc = "1.2"
winresource = "0.1.31"

[package.metadata.bundle]
name = "Parties"
identifier = "rs.parties.app"
icon = ["assets/icons/parties_icon.icns"]
