[package]
name = "parties-rs"
version = "0.1.0"
edition = "2024"

[features]
default = []
native-video = []

[dependencies]
bip39 = "2.2.2"
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
cpal = "0.18.0"
ed25519-dalek = "2.2.0"
getrandom = "0.4.2"
lurq = { path = "../lurq/crates/lurq", features = ["resources", "winit", "image", "wgpu", "devtools", "i18n", "serde", "clipboard", "tokio", "router", "form", "svg"] }
nokhwa = { version = "0.10.11", default-features = false, features = ["input-native"] }
opus = "0.3.1"
quinn = "0.11"
rusqlite = { version = "0.37.0", features = ["bundled"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
sha2 = "0.11.0"
sonora = "0.1.0"
tokio = { version = "1", features = ["rt-multi-thread", "signal", "sync", "time"] }
rdev = "0.5.3"
xcap = "0.9.6"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Media_MediaFoundation", "Win32_System_Com"] }
